# Generated by Django 5.0.6 on 2024-05-16 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('tipo_de_sprite', models.IntegerField()),
                ('entretenimiento', models.IntegerField()),
                ('saciedad', models.IntegerField()),
                ('higiene', models.IntegerField()),
                ('hp', models.IntegerField()),
            ],
        ),
    ]
