# Generated by Django 5.0.6 on 2024-05-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzanas', models.IntegerField(default=10)),
                ('jabones', models.IntegerField(default=10)),
                ('juguetes', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='energia',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='entretenimiento',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='higiene',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='saciedad',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_de_sprite',
            field=models.CharField(choices=[('orejon', 'Orejon'), ('magmitar', 'Magmitar')], max_length=20),
        ),
    ]
