# Generated by Django 4.0.10 on 2024-05-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_items_mascota_energia_alter_mascota_entretenimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='energia',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo_de_sprite',
            field=models.CharField(choices=[('orejon', 'Orejon'), ('magmitar', 'Magmitar'), ('flotante', 'Flotante')], max_length=20),
        ),
    ]
